// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ModuleDome.proto

package net.husky.protobuf;

public final class ModuleDome {
  private ModuleDome() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PluginRequestDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 data = 1;
    boolean hasData();
    int getData();
  }
  public static final class PluginRequestData extends
      com.google.protobuf.GeneratedMessage
      implements PluginRequestDataOrBuilder {
    // Use PluginRequestData.newBuilder() to construct.
    private PluginRequestData(Builder builder) {
      super(builder);
    }
    private PluginRequestData(boolean noInit) {}
    
    private static final PluginRequestData defaultInstance;
    public static PluginRequestData getDefaultInstance() {
      return defaultInstance;
    }
    
    public PluginRequestData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.husky.protobuf.ModuleDome.internal_static_net_husky_protobuf_PluginRequestData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.husky.protobuf.ModuleDome.internal_static_net_husky_protobuf_PluginRequestData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private int data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getData() {
      return data_;
    }
    
    private void initFields() {
      data_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginRequestData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.husky.protobuf.ModuleDome.PluginRequestData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.husky.protobuf.ModuleDome.PluginRequestDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.husky.protobuf.ModuleDome.internal_static_net_husky_protobuf_PluginRequestData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.husky.protobuf.ModuleDome.internal_static_net_husky_protobuf_PluginRequestData_fieldAccessorTable;
      }
      
      // Construct using net.husky.protobuf.ModuleDome.PluginRequestData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.husky.protobuf.ModuleDome.PluginRequestData.getDescriptor();
      }
      
      public net.husky.protobuf.ModuleDome.PluginRequestData getDefaultInstanceForType() {
        return net.husky.protobuf.ModuleDome.PluginRequestData.getDefaultInstance();
      }
      
      public net.husky.protobuf.ModuleDome.PluginRequestData build() {
        net.husky.protobuf.ModuleDome.PluginRequestData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.husky.protobuf.ModuleDome.PluginRequestData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.husky.protobuf.ModuleDome.PluginRequestData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.husky.protobuf.ModuleDome.PluginRequestData buildPartial() {
        net.husky.protobuf.ModuleDome.PluginRequestData result = new net.husky.protobuf.ModuleDome.PluginRequestData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.husky.protobuf.ModuleDome.PluginRequestData) {
          return mergeFrom((net.husky.protobuf.ModuleDome.PluginRequestData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.husky.protobuf.ModuleDome.PluginRequestData other) {
        if (other == net.husky.protobuf.ModuleDome.PluginRequestData.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              data_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 data = 1;
      private int data_ ;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getData() {
        return data_;
      }
      public Builder setData(int value) {
        bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.husky.protobuf.PluginRequestData)
    }
    
    static {
      defaultInstance = new PluginRequestData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.husky.protobuf.PluginRequestData)
  }
  
  public interface PluginResponseDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 data = 1;
    boolean hasData();
    int getData();
  }
  public static final class PluginResponseData extends
      com.google.protobuf.GeneratedMessage
      implements PluginResponseDataOrBuilder {
    // Use PluginResponseData.newBuilder() to construct.
    private PluginResponseData(Builder builder) {
      super(builder);
    }
    private PluginResponseData(boolean noInit) {}
    
    private static final PluginResponseData defaultInstance;
    public static PluginResponseData getDefaultInstance() {
      return defaultInstance;
    }
    
    public PluginResponseData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.husky.protobuf.ModuleDome.internal_static_net_husky_protobuf_PluginResponseData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.husky.protobuf.ModuleDome.internal_static_net_husky_protobuf_PluginResponseData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private int data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getData() {
      return data_;
    }
    
    private void initFields() {
      data_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.husky.protobuf.ModuleDome.PluginResponseData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.husky.protobuf.ModuleDome.PluginResponseData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.husky.protobuf.ModuleDome.PluginResponseDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.husky.protobuf.ModuleDome.internal_static_net_husky_protobuf_PluginResponseData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.husky.protobuf.ModuleDome.internal_static_net_husky_protobuf_PluginResponseData_fieldAccessorTable;
      }
      
      // Construct using net.husky.protobuf.ModuleDome.PluginResponseData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.husky.protobuf.ModuleDome.PluginResponseData.getDescriptor();
      }
      
      public net.husky.protobuf.ModuleDome.PluginResponseData getDefaultInstanceForType() {
        return net.husky.protobuf.ModuleDome.PluginResponseData.getDefaultInstance();
      }
      
      public net.husky.protobuf.ModuleDome.PluginResponseData build() {
        net.husky.protobuf.ModuleDome.PluginResponseData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.husky.protobuf.ModuleDome.PluginResponseData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.husky.protobuf.ModuleDome.PluginResponseData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.husky.protobuf.ModuleDome.PluginResponseData buildPartial() {
        net.husky.protobuf.ModuleDome.PluginResponseData result = new net.husky.protobuf.ModuleDome.PluginResponseData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.husky.protobuf.ModuleDome.PluginResponseData) {
          return mergeFrom((net.husky.protobuf.ModuleDome.PluginResponseData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.husky.protobuf.ModuleDome.PluginResponseData other) {
        if (other == net.husky.protobuf.ModuleDome.PluginResponseData.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              data_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 data = 1;
      private int data_ ;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getData() {
        return data_;
      }
      public Builder setData(int value) {
        bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.husky.protobuf.PluginResponseData)
    }
    
    static {
      defaultInstance = new PluginResponseData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.husky.protobuf.PluginResponseData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_husky_protobuf_PluginRequestData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_husky_protobuf_PluginRequestData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_husky_protobuf_PluginResponseData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_husky_protobuf_PluginResponseData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ModuleDome.proto\022\022net.husky.protobuf\"!" +
      "\n\021PluginRequestData\022\014\n\004data\030\001 \002(\005\"\"\n\022Plu" +
      "ginResponseData\022\014\n\004data\030\001 \002(\005B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_husky_protobuf_PluginRequestData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_husky_protobuf_PluginRequestData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_husky_protobuf_PluginRequestData_descriptor,
              new java.lang.String[] { "Data", },
              net.husky.protobuf.ModuleDome.PluginRequestData.class,
              net.husky.protobuf.ModuleDome.PluginRequestData.Builder.class);
          internal_static_net_husky_protobuf_PluginResponseData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_husky_protobuf_PluginResponseData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_husky_protobuf_PluginResponseData_descriptor,
              new java.lang.String[] { "Data", },
              net.husky.protobuf.ModuleDome.PluginResponseData.class,
              net.husky.protobuf.ModuleDome.PluginResponseData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
