// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package net.husky.protobuf;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MessageHandler
      implements com.google.protobuf.ProtocolMessageEnum {
    HttpGetRequest(0, 18245),
    HttpPostRequest(1, 20559),
    PluginRequest(2, 101),
    PluginResponse(3, 102),
    pluginNotice(4, 104),
    ServerErrorResponse(5, 500),
    ModuleDemoRequest(6, 601),
    ModuleDemoResponse(7, 602),
    ;
    
    public static final int HttpGetRequest_VALUE = 18245;
    public static final int HttpPostRequest_VALUE = 20559;
    public static final int PluginRequest_VALUE = 101;
    public static final int PluginResponse_VALUE = 102;
    public static final int pluginNotice_VALUE = 104;
    public static final int ServerErrorResponse_VALUE = 500;
    public static final int ModuleDemoRequest_VALUE = 601;
    public static final int ModuleDemoResponse_VALUE = 602;
    
    
    public final int getNumber() { return value; }
    
    public static MessageHandler valueOf(int value) {
      switch (value) {
        case 18245: return HttpGetRequest;
        case 20559: return HttpPostRequest;
        case 101: return PluginRequest;
        case 102: return PluginResponse;
        case 104: return pluginNotice;
        case 500: return ServerErrorResponse;
        case 601: return ModuleDemoRequest;
        case 602: return ModuleDemoResponse;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageHandler>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageHandler>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageHandler>() {
            public MessageHandler findValueByNumber(int number) {
              return MessageHandler.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.husky.protobuf.Protocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MessageHandler[] VALUES = {
      HttpGetRequest, HttpPostRequest, PluginRequest, PluginResponse, pluginNotice, ServerErrorResponse, ModuleDemoRequest, ModuleDemoResponse, 
    };
    
    public static MessageHandler valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageHandler(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:net.husky.protobuf.MessageHandler)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protocol.proto\022\022net.husky.protobuf*\301\001\n" +
      "\016MessageHandler\022\024\n\016HttpGetRequest\020\305\216\001\022\025\n" +
      "\017HttpPostRequest\020\317\240\001\022\021\n\rPluginRequest\020e\022" +
      "\022\n\016PluginResponse\020f\022\020\n\014pluginNotice\020h\022\030\n" +
      "\023ServerErrorResponse\020\364\003\022\026\n\021ModuleDemoReq" +
      "uest\020\331\004\022\027\n\022ModuleDemoResponse\020\332\004B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
