// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerError.proto

package net.husky.protobuf;

public final class ServerError {
  private ServerError() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ReturnStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    STATUS_OK(0, 0),
    STATUS_FAIL(1, -100),
    INVALID_REQUEST(2, -1),
    PLUGIN_NOT_FOUND(3, -51),
    PLUGIN_ACTION_NOT_FOUND(4, -52),
    PLUGIN_DATA_NOT_FOUND(5, -53),
    ;
    
    public static final int STATUS_OK_VALUE = 0;
    public static final int STATUS_FAIL_VALUE = -100;
    public static final int INVALID_REQUEST_VALUE = -1;
    public static final int PLUGIN_NOT_FOUND_VALUE = -51;
    public static final int PLUGIN_ACTION_NOT_FOUND_VALUE = -52;
    public static final int PLUGIN_DATA_NOT_FOUND_VALUE = -53;
    
    
    public final int getNumber() { return value; }
    
    public static ReturnStatus valueOf(int value) {
      switch (value) {
        case 0: return STATUS_OK;
        case -100: return STATUS_FAIL;
        case -1: return INVALID_REQUEST;
        case -51: return PLUGIN_NOT_FOUND;
        case -52: return PLUGIN_ACTION_NOT_FOUND;
        case -53: return PLUGIN_DATA_NOT_FOUND;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ReturnStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ReturnStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReturnStatus>() {
            public ReturnStatus findValueByNumber(int number) {
              return ReturnStatus.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.husky.protobuf.ServerError.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ReturnStatus[] VALUES = {
      STATUS_OK, STATUS_FAIL, INVALID_REQUEST, PLUGIN_NOT_FOUND, PLUGIN_ACTION_NOT_FOUND, PLUGIN_DATA_NOT_FOUND, 
    };
    
    public static ReturnStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ReturnStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:net.husky.protobuf.ReturnStatus)
  }
  
  public interface ServerErrorResponseDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .net.husky.protobuf.ReturnStatus error = 1;
    boolean hasError();
    net.husky.protobuf.ServerError.ReturnStatus getError();
  }
  public static final class ServerErrorResponseData extends
      com.google.protobuf.GeneratedMessage
      implements ServerErrorResponseDataOrBuilder {
    // Use ServerErrorResponseData.newBuilder() to construct.
    private ServerErrorResponseData(Builder builder) {
      super(builder);
    }
    private ServerErrorResponseData(boolean noInit) {}
    
    private static final ServerErrorResponseData defaultInstance;
    public static ServerErrorResponseData getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServerErrorResponseData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.husky.protobuf.ServerError.internal_static_net_husky_protobuf_ServerErrorResponseData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.husky.protobuf.ServerError.internal_static_net_husky_protobuf_ServerErrorResponseData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .net.husky.protobuf.ReturnStatus error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private net.husky.protobuf.ServerError.ReturnStatus error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public net.husky.protobuf.ServerError.ReturnStatus getError() {
      return error_;
    }
    
    private void initFields() {
      error_ = net.husky.protobuf.ServerError.ReturnStatus.STATUS_OK;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasError()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, error_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, error_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.husky.protobuf.ServerError.ServerErrorResponseData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.husky.protobuf.ServerError.ServerErrorResponseData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.husky.protobuf.ServerError.ServerErrorResponseDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.husky.protobuf.ServerError.internal_static_net_husky_protobuf_ServerErrorResponseData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.husky.protobuf.ServerError.internal_static_net_husky_protobuf_ServerErrorResponseData_fieldAccessorTable;
      }
      
      // Construct using net.husky.protobuf.ServerError.ServerErrorResponseData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        error_ = net.husky.protobuf.ServerError.ReturnStatus.STATUS_OK;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.husky.protobuf.ServerError.ServerErrorResponseData.getDescriptor();
      }
      
      public net.husky.protobuf.ServerError.ServerErrorResponseData getDefaultInstanceForType() {
        return net.husky.protobuf.ServerError.ServerErrorResponseData.getDefaultInstance();
      }
      
      public net.husky.protobuf.ServerError.ServerErrorResponseData build() {
        net.husky.protobuf.ServerError.ServerErrorResponseData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private net.husky.protobuf.ServerError.ServerErrorResponseData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        net.husky.protobuf.ServerError.ServerErrorResponseData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public net.husky.protobuf.ServerError.ServerErrorResponseData buildPartial() {
        net.husky.protobuf.ServerError.ServerErrorResponseData result = new net.husky.protobuf.ServerError.ServerErrorResponseData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.husky.protobuf.ServerError.ServerErrorResponseData) {
          return mergeFrom((net.husky.protobuf.ServerError.ServerErrorResponseData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.husky.protobuf.ServerError.ServerErrorResponseData other) {
        if (other == net.husky.protobuf.ServerError.ServerErrorResponseData.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasError()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              net.husky.protobuf.ServerError.ReturnStatus value = net.husky.protobuf.ServerError.ReturnStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                error_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .net.husky.protobuf.ReturnStatus error = 1;
      private net.husky.protobuf.ServerError.ReturnStatus error_ = net.husky.protobuf.ServerError.ReturnStatus.STATUS_OK;
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public net.husky.protobuf.ServerError.ReturnStatus getError() {
        return error_;
      }
      public Builder setError(net.husky.protobuf.ServerError.ReturnStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = net.husky.protobuf.ServerError.ReturnStatus.STATUS_OK;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.husky.protobuf.ServerErrorResponseData)
    }
    
    static {
      defaultInstance = new ServerErrorResponseData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.husky.protobuf.ServerErrorResponseData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_husky_protobuf_ServerErrorResponseData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_husky_protobuf_ServerErrorResponseData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ServerError.proto\022\022net.husky.protobuf\"" +
      "J\n\027ServerErrorResponseData\022/\n\005error\030\001 \002(" +
      "\0162 .net.husky.protobuf.ReturnStatus*\276\001\n\014" +
      "ReturnStatus\022\r\n\tSTATUS_OK\020\000\022\030\n\013STATUS_FA" +
      "IL\020\234\377\377\377\377\377\377\377\377\001\022\034\n\017INVALID_REQUEST\020\377\377\377\377\377\377\377" +
      "\377\377\001\022\035\n\020PLUGIN_NOT_FOUND\020\315\377\377\377\377\377\377\377\377\001\022$\n\027PL" +
      "UGIN_ACTION_NOT_FOUND\020\314\377\377\377\377\377\377\377\377\001\022\"\n\025PLUG" +
      "IN_DATA_NOT_FOUND\020\313\377\377\377\377\377\377\377\377\001B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_husky_protobuf_ServerErrorResponseData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_husky_protobuf_ServerErrorResponseData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_husky_protobuf_ServerErrorResponseData_descriptor,
              new java.lang.String[] { "Error", },
              net.husky.protobuf.ServerError.ServerErrorResponseData.class,
              net.husky.protobuf.ServerError.ServerErrorResponseData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
